In [2]:
import numpy as np
import pandas as pd

In [6]:
a=np.array([2,4,55,7,9,13,21])
b=np.array([3,5,88,12,4,5,6])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False False False  True  True  True]
[False False False False  True  True  True]
[ True  True  True  True False False False]
[ True  True  True  True False False False]


In [13]:
a=np.zeros(5)
b=np.ones(5)
c=np.full(5,5)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[5 5 5 5 5]


In [17]:
arr=np.array([[1,6,7,8],[5,9,8,4],[3,87,12,0]])
print(arr.sum())
print(arr.sum(axis=1))
print(arr.sum(axis=0))

150
[ 22  26 102]
[  9 102  27  12]


In [20]:
a=np.array([1,5,7,8,9,3])
b=np.array([2,5,82,99,1,7])
print(a*b)
print(a+b)
print(a-b)
print(a/b)

[  2  25 574 792   9  21]
[  3  10  89 107  10  10]
[ -1   0 -75 -91   8  -4]
[0.5        1.         0.08536585 0.08080808 9.         0.42857143]


In [22]:
dicto={'name':['veer','jahn','guna','adi'],'score':[25,13,45,12]}
df=pd.DataFrame(dicto)
df.head()

name  score
0  veer     25
1  jahn     13
2  guna     45
3   adi     12

In [24]:
df[['name','score']]

name  score
0  veer     25
1  jahn     13
2  guna     45
3   adi     12

In [27]:
df.isna()

name  score
0  False  False
1  False  False
2  False  False
3  False  False

In [29]:
ob=pd.Series([1,4,6,7,8,9])
print(ob)

0    1
1    4
2    6
3    7
4    8
5    9
dtype: int64
